/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ApprovalStatus: typeof import('./src/components/recruiter/ApprovalStatus.vue')['default']
    CustomColumnChooser: typeof import('./src/components/base/table/CustomColumnChooser.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    MDialog: typeof import('./src/components/base/dialog/MDialog.vue')['default']
    MInput: typeof import('./src/components/base/input/MInput.vue')['default']
    MInputDate: typeof import('./src/components/base/input/MInputDate.vue')['default']
    MInputSelectBox: typeof import('./src/components/base/input/MInputSelectBox.vue')['default']
    MLoading: typeof import('./src/components/base/loading/MLoading.vue')['default']
    MSelectbox: typeof import('./src/components/base/input/MSelectbox.vue')['default']
    MTable: typeof import('./src/components/base/table/MTable.vue')['default']
    MTextArea: typeof import('./src/components/base/input/MTextArea.vue')['default']
    Role: typeof import('./src/components/accounts/Role.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Status: typeof import('./src/components/accounts/Status.vue')['default']
    TheAdminLayout: typeof import('./src/components/layout/TheAdminLayout.vue')['default']
    TheAuthLayout: typeof import('./src/components/layout/TheAuthLayout.vue')['default']
    TheContent: typeof import('./src/components/layout/content/TheContent.vue')['default']
  }
}
