/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CustomColumnChooser: typeof import('./src/components/base/table/CustomColumnChooser.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    MDialog: typeof import('./src/components/base/dialog/MDialog.vue')['default']
    MInput: typeof import('./src/components/base/input/MInput.vue')['default']
    MInputDate: typeof import('./src/components/base/input/MInputDate.vue')['default']
    MInputSelectBox: typeof import('./src/components/base/input/MInputSelectBox.vue')['default']
    MLoading: typeof import('./src/components/base/loading/MLoading.vue')['default']
    MSelectbox: typeof import('./src/components/base/input/MSelectbox.vue')['default']
    MTable: typeof import('./src/components/base/table/MTable.vue')['default']
    MTextArea: typeof import('./src/components/base/input/MTextArea.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Src: typeof import('./src/components/Category/src/index.vue')['default']
    TheAdminLayout: typeof import('./src/components/layout/TheAdminLayout.vue')['default']
    TheAuthLayout: typeof import('./src/components/layout/TheAuthLayout.vue')['default']
    TheContent: typeof import('./src/components/layout/content/TheContent.vue')['default']
    VerifyCode: typeof import('./src/components/VerifyCode/index.vue')['default']
  }
}
